# Generated by Django 5.2.7 on 2026-01-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_attributes'),
        ('wallet', '0002_transaction_authority_transaction_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='posts.post'),
        ),
    ]
