# Generated by Django 5.2.8 on 2026-02-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category_and_more'),
        ('wallet', '0004_alter_transaction_post_alter_transaction_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='posts.post'),
        ),
    ]
