# Generated by Django 5.2.8 on 2026-02-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category_and_more'),
        ('wallet', '0005_alter_transaction_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='posts.post'),
        ),
    ]
