# Generated by Django 5.2.8 on 2025-11-26 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', through='social.UserFollow', to=settings.AUTH_USER_MODEL),
        ),
    ]
