# Generated by Django 5.2.8 on 2025-12-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_image_remove_post_video_categoryformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
